### ISSUE TITLE
[Bug] Dependencies not listed in environment file

### ISSUE THREAD

**Issue by JulianLopezB** [facebookresearch/nocturne#54]
### Bug description

There are some dependencies that are not listed in `environment.yml`, e.g: 

- hydra
- gym
- PyVirtualDisplay

### Steps to reproduce

```
git clone https://github.com/facebookresearch/nocturne.git
cd nocturne
git submodule sync
git submodule update --init --recursive

# create the environment and install the dependencies
conda env create -f environment.yml

# activate the environment where the Python library should be installed
conda activate nocturne

# run the C++ build and install Nocturne into the simulation environment
python setup.py develop

# run example
python examples/create_env.py
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "examples/create_env.py", line 10, in <module>
    from nocturne.envs.wrappers import create_env
  File "/Users/julian/Desktop/Projects/RL/nocturne/nocturne/envs/__init__.py", line 2, in <module>
    from nocturne.envs.base_env import BaseEnv
  File "/Users/julian/Desktop/Projects/RL/nocturne/nocturne/envs/base_env.py", line 13, in <module>
    from gym import Env
ModuleNotFoundError: No module named 'gym'
```

**Comment by eugenevinitsky** [comment]
Thank you for pointing this out! We'll add these to the requirements.
