### ISSUE TITLE
[Bug] python examples/imitation_learning/train.py

### ISSUE THREAD

**Issue by RyanXXX123** [facebookresearch/nocturne#74]
### Operating system

python examples/imitation_learning/train.py

### Bug description

python examples/imitation_learning/train.py 

### Steps to reproduce

run python examples/imitation_learning/train.py
than choose option 3

### Relevant log output

```shell
(nocturne) root@ryan:/home/ryan/nocturne# python examples/imitation_learning/train.py
WaymoDataset: loading 1000 files.
ImitationAgent(
  (nn): Sequential(
    (0): MeanStdFilter()
    (1): Linear(in_features=35110, out_features=1024, bias=True)
    (2): Tanh()
    (3): Sequential(
      (0): Linear(in_features=1024, out_features=256, bias=True)
      (1): Tanh()
    )
    (4): Sequential(
      (0): Linear(in_features=256, out_features=128, bias=True)
      (1): Tanh()
    )
  )
  (heads): ModuleList(
    (0): Linear(in_features=128, out_features=15, bias=True)
    (1): Linear(in_features=128, out_features=43, bias=True)
  )
)
Wrote configs at /checkpoint/root/nocturne/test/2023.11.08/test/09.54.05/train_logs/2023_11_08_09_54_07/configs.json
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
wandb: ERROR Error while calling W&B API: user is not logged in (<Response [401]>)
Thread SenderThread:
Traceback (most recent call last):
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1318, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/util.py", line 875, in no_retry_auth
    raise CommError("Invalid or missing api_key. Run `wandb login`")
wandb.errors.CommError: Invalid or missing api_key. Run `wandb login`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 310, in _process
    self._sm.send(record)
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 234, in send
    send_handler(record)
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 692, in send_run
    self._init_run(run, config_value_dict)
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 716, in _init_run
    server_run, inserted = self._api.upsert_run(
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/apis/normalize.py", line 58, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1318, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/root/anaconda3/envs/nocturne/lib/python3.8/site-packages/wandb/util.py", line 875, in no_retry_auth
    raise CommError("Invalid or missing api_key. Run `wandb login`")
wandb.errors.CommError: Invalid or missing api_key. Run `wandb login`
wandb: ERROR Internal wandb error: file data was not synced
```

**Comment by eugenevinitsky** [comment]
Hey Ryan, check out a recent fork that we're working on incorporating back. It's cleaned up a lot: https://github.com/Emerge-Lab/nocturne_lab. We're working on merging the fixes to this bug back into here
